export { AdminLoginPage } from './AdminLoginPage';
export { DashboardPage } from './DashboardPage';
export { AdminHistoryPage } from './HistoryPage';
export { AdminQualityPage } from './QualityPage';
export { EfficiencyPage } from './EfficiencyPage';
export { RatesPage } from './RatesPage';
export { CostingPage } from './CostingPage';
export { MaintenancePage } from './MaintenancePage';
export { BearingsPage } from './BearingsPage';
export { ProductsPage } from './ProductsPage';
export { MachinesPage as AdminMachinesPage } from './MachinesPage';
export { CustomersPage } from './CustomersPage';
export { CustomerDetailPage } from './CustomerDetailPage';
export { UsersPage } from './UsersPage';
